### ISSUE TITLE
Arrow function is a breaking change for node v0.10

### ISSUE THREAD

**Issue by xavi-** [Mithgol/node-uue#5]
[Using the arrow functions](https://github.com/Mithgol/node-uue/commit/10299ec627ad4ca9b3960acc7bbe49a11c0a7b1d) in v3.1.1 breaks projects still on node v0.10.x.  I realize that node v0.10 is very old and should be upgraded, but that's the world we live in.

Any chance v3.1.1 could be unpublish and be re-published as v4.0.0?

Appreciate the help.

**Comment by Mithgol** [comment]
The major version change (that reflected breaking changes in my support of older Node.js versions) happened in v3.0.0. Starting from v3.0.0, this module requires Node.js version 4.0.0 or newer, and I have relied not only on arrow functions but on `Array.prototype.findIndex` as well.

In addition to being merely old, Node.js v0.10 has also met its official end of life more than a year ago and thus it does not receive even critical bugfixes from its developers. Therefore its use is gradually becoming more dangerous and I won't support that old version of the engine. You'll have to make a fork and help yourself.
